### ISSUE TITLE
Enhancement suggestion: Change the colors used for the tabs background.

### ISSUE THREAD

**Issue by Gittino** [Revivius/nb-darcula#88] opened 2016-04-01 09:59 UTC
Hi,
this is a very nice theme, IMHO the best dark theme for NetBeans.
I would like to leave a suggestion as I work with the tabs colored basing on the project to which the file pertain.

(This option is located in "Options"-> "Appearance"->"Document Tabs" -> "Same background color for files from the same project".) 

The default colors used for the tabs backgrounds are too light and don't fit with the rest of the darcula theme. Would be nice if you could adapt also them to the darcula style.
Thanks and best regards.

**Comment by markiewb** [comment] 2016-04-01 18:47
@Revivius: Duplicate of #85

**Comment by Gittino** [comment] 2016-04-02 08:00
@markiewb : Hi Markiewb, actually this is not a duplicate of bug 85. The bug 85 reports an issue (the tabs background is colored only for one of the projects so the features in that case doesn' t work properly). 
My request is more an enhancement and concerns the color palette used for the tab backgrounds. 
In fact as you can see from the image posted in bug 85 the color used for the tab backgrounds is very light and doesn't fit with the darcula theme. I would like that the color palette would be changed to one a bit more coherent with dark theme if possible.
Thanks a lot!

**Closed** 2016-04-03 12:42 UTC

**Comment by Revivius** [comment] 2016-04-03 12:52
@Gittino, @4ppleboy; I dont use "Same background color for files from the same project" feature and sure there would be different suggestions about which colors to use for different projects. So instead I just decreased numeric values of R,G,B components of current colors. See

http://hg.netbeans.org/main/file/47dbbfccbac4/core.multitabs/src/org/netbeans/core/multitabs/impl/ProjectColorTabDecorator.java

I think these colors are usable enough:

![project-colors](https://cloud.githubusercontent.com/assets/7155989/14232406/812f88c8-f9b3-11e5-830a-6dc12c5df3bb.png)

![project-colors2](https://cloud.githubusercontent.com/assets/7155989/14232407/879f7060-f9b3-11e5-9a53-853a72064365.png)

**Comment by markiewb** [comment] 2016-04-03 17:06
@Revivius: Good job. Though consider to provide a own org.netbeans.core.multitab.TabDecorator instead of going the reflections-approach to set the colors! It's public API
