### ISSUE TITLE
1.4 -> 1.5 Update doesn't seem to install

### ISSUE THREAD

**Issue by swebb99uk** [Revivius/nb-darcula#98] opened 2016-04-19 16:31 UTC
When I run up Netbeans (8.1) it tells me that there is an update available. I go through the normal steps to update and restart the IDE and it still tells me there is an update available. I don't see any kind of errors.

**Comment by Revivius** [comment] 2016-04-27 12:01
@swebb99uk; update works ok for me. Problem persists ?

**Comment by swebb99uk** [comment] 2016-04-27 13:37
Hi there,

I tried a few times and it didn't update. However I just tried again as there was a list of other updates and they all failed initially. BUT I have been running netbeans via a shortcut icon on my ubuntu 15.10 box and I thought to myself what happens if I run up netbeans via './netbeans' rather than the shortcut, it has now updated everything after showing me the update wizard as it started!!!!

So it is working now :) Not sure what the problem was with starting from a shortcut.

**Comment by Revivius** [comment] 2016-04-28 08:44
@swebb99uk; works for me. Closing this issue.

**Closed by Revivius** 2016-04-28 08:44 UTC

**Comment by voghDev** [comment] 2018-07-23 11:17
This issue has just happened to me. I can confirm that my cause was running Netbeans from a Desktop Icon. When running it from console with 

`./netbeans`

 plugin installation worked fine
