### ISSUE TITLE
L&F breaks tab navigation

### ISSUE THREAD

**Issue by cowwoc** [Revivius/nb-darcula#101] opened 2016-04-26 17:01 UTC
In NetBeans IDE Dev (Build 201604210001), you can use CTRL+PageUp/PageDown to navigate through Editor tabs but the minute you install Darcula 1.4 these shortcut keys stop working.

I believe that this worked with the Netbeans build from last week, so something must have changed on their end. Please investigate this ASAP because it is a major pain working without these keys.

**Comment by cowwoc** [comment] 2016-04-26 17:13
Filed https://netbeans.org/bugzilla/show_bug.cgi?id=259025

**Comment by Revivius** [comment] 2016-04-26 17:51
@cowwoc; works ok with NB 8.1 and Darcula v1.4. Lets see the response from NetBeans bugzilla.

As a side question: why v1.4 ? v1.5 should be available.

**Comment by cowwoc** [comment] 2016-04-26 18:33
Odd.

I now see this problem in NetBeans IDE Dev (Build 201604060001) with either Darcula 1.4 or 1.5.

The only other change I can think of is that I upgraded from JDK8 update 77 to 92. Can you please try JDK8 update 92 on your end?

**Comment by Revivius** [comment] 2016-04-27 11:52
@cowwoc; seems to be fixed in latest dev builds as duplicate of https://netbeans.org/bugzilla/show_bug.cgi?id=258939

Closing this issue.

**Closed by Revivius** 2016-04-27 11:52 UTC

**Comment by cowwoc** [comment] 2016-05-03 19:10
@Revivius Please reopen this issue. I am able to reproduce this bug in Netbeans build:

Product Version: NetBeans IDE Dev (Build 201605020002)
Java: 1.8.0_92; Java HotSpot(TM) 64-Bit Server VM 25.92-b14
Runtime: Java(TM) SE Runtime Environment 1.8.0_92-b14
System: Windows 7 version 6.1 running on amd64; UTF-8; en_US (nb)
User directory: C:\dev\Netbeans\user\dev
Cache directory: C:\dev\Netbeans\cache\dev

with Darcula 1.5 installed. According to https://netbeans.org/bugzilla/show_bug.cgi?id=258939 the aforementioned bug was fixed in Netbeans.

This means the remaining bug could be in Darcula itself. Again, please note my JDK8 version and OS might be different than yours. Try to match it as much as possible.

**Comment by Revivius** [comment] 2016-07-13 00:32
@cowwoc; I am running NB 8.1 on Windows 10 and CTRL+PageUp/PageDown works for me. Can you please validate the issue ?

**Comment by cowwoc** [comment] 2016-07-13 00:34
This issue only affects dev builds (newer than 8.1). Please try those.
