### ISSUE TITLE
Backround after right click

### ISSUE THREAD

**Issue by kowern** [Revivius/nb-darcula#71] opened 2016-02-03 21:31 UTC
Background after right mouse click change into two colors. I my opinion doesn't look good. 

![zrzut-ekranu- 63](https://cloud.githubusercontent.com/assets/16614575/12797747/c90d3d2e-cac5-11e5-9660-4a68b01cef57.png)

**Comment by markiewb** [comment] 2016-02-03 21:44
Duplicate of #5

**Comment by Revivius** [comment] 2016-02-03 21:46
Closing, as duplicate.

**Closed by Revivius** 2016-02-03 21:46 UTC
