### ISSUE TITLE
Import Classes are not readable after paste code

### ISSUE THREAD

**Issue by Saljack** [Revivius/nb-darcula#30] opened 2016-01-25 08:27 UTC
If I paste code then Import Classes dialog is showed. Where classes are not readable. 
![import](https://cloud.githubusercontent.com/assets/614424/12545818/a8cd72f4-c345-11e5-885a-38a71013f168.PNG)
Maybe it is same issue as #22

**Comment by dylanvorster** [comment] 2016-01-25 09:11
Yeah I think this is the same issue, perhaps we should close it as fixing the problem in #22 will definitely solve this problem.

**Comment by Revivius** [comment] 2016-01-26 06:04
Duplicate of #22. Will be fixed in v1.4, closing this one.

**Closed by Revivius** 2016-01-26 06:04 UTC
Labels: duplicate
