### ISSUE TITLE
Control+PageUp/Down don't work on netbeans 8.2

### ISSUE THREAD

**Issue by okvorb** [Revivius/nb-darcula#126] opened 2016-10-19 20:56 UTC
Hi

Recently I upgraded netbeans from 8.1 to 8.2 and noticed that Ctrl+PageUp/Down shortcut doesn't work anymore. I thought it's netbeans issue itself, but then I tried fresh installation and found that shortcut don't work only with darcula theme.

**Comment by markiewb** [comment] 2016-10-19 21:01
Duplicate of #114!

**Comment by Revivius** [comment] 2017-07-30 07:46
Fixed in 6fd446377913bc9b2f4891430307354997973702. Thanks to @markiewb.

**Closed by Revivius** 2017-07-30 07:46 UTC
Labels: duplicate
