### ISSUE TITLE
Problem with constructor generation in PHP

### ISSUE THREAD

**Issue by bazo** [Revivius/nb-darcula#57] opened 2016-01-30 11:41 UTC
normally when you press alt+insert and select constructor you can press enter to generate the constructor with selected fields

with this plugin active enter doesn't work like this anymore, it just toggles the class properties dropdown

after deactivating the plugin it works as before

**Comment by markiewb** [comment] 2016-01-30 11:56
Duplicate of https://github.com/Revivius/nb-darcula/issues/14 ?

**Comment by bazo** [comment] 2016-01-30 12:03
oh, sorry. i just read the issue titles, didn't connect that issue with this problem

**Comment by markiewb** [comment] 2016-01-30 12:16
That's fine. I wrote a comment at the other issue to the maintainer to fix it's title, so that it is obvious

**Comment by Revivius** [comment] 2016-01-30 13:22
Closing as duplicate of #14.

**Closed by Revivius** 2016-01-30 13:22 UTC
Labels: duplicate
