### ISSUE TITLE
Highlighting color of code on exception makes the line unreadable

### ISSUE THREAD

**Issue by birgersp** [Revivius/nb-darcula#112] opened 2016-06-13 08:50 UTC
Hi,

When stack trace is printed, the source code line causing the exception is highlighted in light red. This makes the code in that line extremely hard to see.

In this screenshot, line 89 is highlighted. (Note I have am partly colorblind, so this might look different to you. But to me, it's virtually impossible to read the code in the highlighted line).

![screenshot from 2016-06-13 10-44-41](https://cloud.githubusercontent.com/assets/5260237/16001772/54dda196-3154-11e6-9f31-22e5ac0741de.png)

**Comment by Revivius** [comment] 2016-07-13 00:52
@birgersp; thank you for reporting. I dont know how to reproduce to issue but by looking at the icon on line 89 and background/foreground colors from **Options > Fonts & Colors > Annotations** all similar annotations (errors) would result in unreadable lines.

@granella can you help about this please ?

**Comment by granella** [comment] 2016-07-13 22:16
@birgersp this is the default color for the Netbeans theme. For some reason, didn't change for the Darcula theme. 

See the image the default color of Darcula theme:
![screenshot from 2016-07-13 18 43 21](https://cloud.githubusercontent.com/assets/859038/16820910/d94ff522-4929-11e6-9e52-2fdd76b78245.png)

I don't know a way to change colors via code to meet you needs, but you can change colors to make it more visible in "Options" > "Fonts & Colors" > "Annotations"

**Comment by markiewb** [comment] 2016-07-23 14:26
My proposal: Close this issue as invalid because @birgersp did not give any feedback.

**Comment by birgersp** [comment] 2016-07-23 16:47
Sorry that I did not comment sooner. I guess it's just a problem at my end then. I thought it would be the same for more people since I couldn't figure out how to set this color manually. I'll try to fix it here. I agree about closing this issue

**Comment by Revivius** [comment] 2016-07-23 22:57
Closing as suggested.

**Closed by Revivius** 2016-07-23 22:57 UTC
