### ISSUE TITLE
Autocomplete of custom HTML elements are hard to read

### ISSUE THREAD

**Issue by TobiasKrahn** [Revivius/nb-darcula#106] opened 2016-05-11 11:42 UTC
Maybe just another hardcoded color. 
![ac](https://cloud.githubusercontent.com/assets/16705453/15179673/927c430e-177d-11e6-8d9d-db6e8e78eb4b.png)

**Comment by markiewb** [comment] 2016-07-23 14:32
Provide sample code for reproduction! I do not know, which filetype is it!

**Comment by Revivius** [comment] 2016-07-23 23:05
@TobiasKrahn is this for Angular Material ?

**Comment by TobiasKrahn** [comment] 2016-07-23 23:25
@markiewb It's just a html file. You should be able to reproduce it like this:
1. Create a html project 
2. Enter some tags, that doesn't exist
3. Click on the warning 
4. Click add to project custom Elements 
5. Use the added tag again with autocomplete 

Sorry, that I can't provide any example. I'm currently on vacation :-). 

@Revivius Yes, its angularjs or more specifically Angular Material element directives.

**Comment by Revivius** [comment] 2016-07-24 00:29
@TobiasKrahn, @markiewb same problem: https://netbeans.org/bugzilla/show_bug.cgi?id=257867. We need more votes for that bug.

In the meantime fixed with reflection.

**Closed by Revivius** 2016-07-24 00:29 UTC

**Comment by Chris2011** [comment] 2017-08-01 15:05
I have the same problem with this plugin: https://github.com/hexaviewtech/ionic-netbeans-plugin

Here is the screenshot:
![ionic-code-completion](https://user-images.githubusercontent.com/795658/28831977-928fce74-76db-11e7-987a-05dfc5a635c8.png)

**Comment by Revivius** [comment] 2017-08-01 18:19
@Chris2011; as you might already know: code completion item colors are provided by the author of respective module/plugin. We have been replacing hardcoded colors in standard modules (such as SQL editor, HTML editor, etc) using reflection but it is not feasible to hack every single CompletionItem implementation. Module authors should check UIManager.getBoolean("nb.dark.theme") (assuming all dark look and feels set this to true as nb-darcula does) and provide alternate colors that are reasonably readable on a dark background. 

In this specific case: it is this line causing hard to read color:

https://github.com/hexaviewtech/ionic-netbeans-plugin/blob/master/src/com/hexaview/ionicextension/IonicTagCompletionItem.java#L38

Please report the issue to ionic-netbeans-plugin.

**Comment by Chris2011** [comment] 2017-08-01 18:31
Thx for the explanation. I only thought because you fixed it for the above Plugin it was fixed in General.
