### ISSUE TITLE
Low contrast for popup drop-down lists in SQL editor for field names

### ISSUE THREAD

**Issue by DVader666** [Revivius/nb-darcula#80] opened 2016-02-26 16:14 UTC
In the NB SQL editor, when using code completion while working with queries, the drop-down list popup contains low contrast colors for DB table field names: dark background with dark blue font color (for items not currently selected in the list).

Currently using NB 8.1 (up to date).

![image](https://cloud.githubusercontent.com/assets/17498743/13357757/841f1ddc-dc71-11e5-8787-ad6301cb52d7.png)

**Comment by AlexFalappa** [comment] 2016-02-27 12:25
Duplicate of #67.
Already fixed but not released yet.

**Comment by Revivius** [comment] 2016-02-29 20:47
@DVader666 fix will be available in v1.5. Thank you for reporting.

**Closed by Revivius** 2016-02-29 20:47 UTC
Labels: duplicate
